#!/bin/bash


# Error handling
set -euo pipefail

# Only run the script and apply if the chezmoi binary is not found (output is not 0)
if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:lassebischoff/dotfiles-demo.git
fi

sudo apt update && sudo apt install vim -y 

exit 0
